runtime: python37

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
#- url: /static
#  static_dir: static

- url: /favicon.ico
  static_files: media/img/favicon.ico
  upload: media/img/favicon.ico
  
- url: /
  script: auto

- url: .*
  script: auto
