runtime: python37

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.

  #added favicon due to gcp crashing (status 500) without it
- url: /favicon.ico
  static_files: media/img/favicon.ico
  upload: media/img/favicon.ico

  #google seems inconsistent when uploading static files, and when updating these files.
  #welcome.html is in root project folder and in web/static/ because gcp updates very slowly, and I'm not exactly sure which one it's updating from so I've included both.
  #I believe it's the one in web/static/ since I've specified it below, but I can't be certain, so I've left both in.
- url: /welcome
  static_files: web/static/welcome.html
  upload: web/static/welcome.html

- url: /
  script: auto

- url: .*
  script: auto
